### ISSUE TITLE
Error running Import-VisualStudioEnvironment

### ISSUE THREAD

**Issue by stuartleeks** [Wintellect/WintellectPowerShell#4]
I get the error below when I run Import-VisualStudioEnvironment:

```
'"C:\Program Files (x86)\Microsoft Visual Studio 14.0\\vc\vcvarsall.bat"' is not recognized as an internal or external command, operable program or batch file.
ERROR: Error executing CMD.EXE: 1
```

Checking "C:\Program Files (x86)\Microsoft Visual Studio 14.0\\vc\", the vcvarsall.bat doesn't exist. I think I did a fairly minimal install on this machine (C# + Web tools). There is a Developer Command Prompt for VS2015 in my Start Menu, and checking the properties for that it launches "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat"

**Comment by JohnWintellect** [comment]
Thanks, Stuart! I really appreciate the bug report. All fixed now.
