### ISSUE TITLE
Does not work with projects without Debug / Release configs

### ISSUE THREAD

**Issue by francofs** [Wintellect/WintellectPowerShell#5]
I tried to use Set-ProjectProperties, but my Projects do not have Debug / Release configuration. I have my own custom configurations and maybe this is hardcoded in the module.

**Comment by JohnWintellect** [comment]
Look at the -Configurations and -CustomConfigurationProperties parameters. I hard coded Debug + Release as 99.99999% of projects have those configurations. Is this an internationalization issue?

**Comment by francofs** [comment]
Oh sorry, thanks for the pointer, I got it working after reading the source code. Maybe as a todo you could have the parameters on the readme.

Now it works. My configs are DEV, UAT, PRD. This is our continuous integration configurations so, that's why. We have automatic transformations for the configurations file that requires it to be this way.

Thanks again and nice work! It saved me a lot of time. I have over 40 projects in my solution.

**Comment by JohnWintellect** [comment]
Very cool! Glad to hear the module saved you some time. My day has been made! :+1: 

These parameters are shown in the Set-ProjectProperties help (see the last example). Is that sufficient?

**Comment by francofs** [comment]
Oh yes, that is sufficient, I think I may have missed the example, but it's
all good now :)

Thanks again. All the best!
